# run with treefmt --allow-missing-formatter

[global]
excludes = [
  # models and data
  "**/models/*.onnx",
  "**/models/*.txt",
  "**/testdata/*.jpg",
  "**/testdata/*.png",
  "**/testdata/*.pdf",
  # sops
  "**/secrets.{yaml,json}",
  "**/*.sops.*",
  # release please
  "CHANGELOG.md",
  # txt files
  "**/*.txt",
  "version.txt",
  # gitignore
  "**/.gitignore",
  # go.sum & go.mod
  "go.sum",
  "go.mod",
  # justfile
  "justfile",
]

### Misc

[formatter.prettier]
command = "prettier"
options = ["-w"]
includes = [
  "*.graphql",
  "*.html",
  "*.css",
  "*.yaml",
  "*.yml",
  "*.js",
  "*.json",
  "*.md",
]
excludes = [".release-please-manifest.json"]

### Go

[formatter.gofumpt]
command = "gofumpt"
options = ["-w"]
includes = ["*.go"]

[formatter.gci]
command = "gci"
options = ["-w"]
includes = ["*.go"]
priority = 1        # run after gofumpt

### Shell

[formatter.shellcheck]
command = "shellcheck"
includes = ["*.sh"]

[formatter.shfmt]
command = "shfmt"
options = ["-s", "-w"]
includes = ["*.sh"]
priority = 1           # run after shellcheck

### Just

[formatter.just]
command = "just"
options = ["--fmt", "--unstable", "--justfile"]
includes = ["justfile", "*.just", "Justfile"]

### TOML

[formatter.taplo]
command = "taplo"
options = ["fmt"]
includes = ["*.toml"]

### YAML

[formatter.yamlfmt]
command = "yamlfmt"
options = ["format", "-"]
includes = ["*.yaml", "*.yml"]

### Docker

[formatter.dockerfmt]
command = "dockerfmt"
includes = ["Dockerfile", "*.Dockerfile"]
