name: test-lint
on:
  workflow_call:
permissions:
  contents: read
jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Install Just
        uses: extractions/setup-just@v2
        with:
          just-version: 1.14.0
      - name: Setup ONNX Runtime
        uses: ./.github/actions/setup-onnxruntime
      - name: Check tidy
        run: just check-tidy
      - name: Run linter
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: --timeout 5m
